server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.1.102:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomzhan/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: 192.168.1.102

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
