server:
  port: 8888

eureka:
  instance:
    hostname: 192.168.1.5
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
