spring:
  application:
    name: zipkin
  rabbitmq:
    host: 192.168.1.102
    port: 15673
    username: guest
    password: guest

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
