logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

server:
  port: 8040

turbine:
  stream:
    port: 8041

eureka:
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.1.102:8761/eureka/

spring:
  rabbitmq:
    host: 192.168.1.102
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://192.168.1.102:${turbine.stream.port}

security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}