server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.5.185
#    prefer-ip-address: true
    ip-address: 192.168.5.185
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.5.185:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    
    
security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
